server:
  port: 8001

mybatis:
  type-aliases-package: com.liang.pojo
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    cache-enabled: true

spring:
  application:
    name: springclould-dept
  datasource:                                           # 数据源的相关配置
    type: com.alibaba.druid.pool.DruidDataSource         # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 500

eureka:
  client: #将客户端注册进eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springclould-dept8001  #自定义服务名称
    prefer-ip-address: true #访问路径可以显示ip地址

info:
  app.name: springclould-dept
  company.name: https://github.com/liangyehao
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}